"""add create to audit action enum

Revision ID: b1eccc6417f6
Revises: d09bf318491e
Create Date: 2026-06-11 18:26:39.192184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1eccc6417f6'
down_revision: Union[str, Sequence[str], None] = 'd09bf318491e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE auditactiontype ADD VALUE IF NOT EXISTS 'create'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
